### ISSUE TITLE
Produce plots for memory usage

### ISSUE THREAD

**Issue by mdboom** [faster-cpython/bench_runner#137]
It would be interesting to see memory usage plots, just as we have time plots.

The existing data has `max_rss` for each of the benchmark runs -- as a start, we can use that (though it's pretty large-grained).  If that doesn't seem helpful, maybe we investigate add a small amount of memory tracking to the pystats and using that.

Cc: @brandtbucher (for the idea)

**Comment by mdboom** [comment]
Added in #138.

This is based on the “max_rss” support that pyperf has had for a long time, for which we already have data.  This is pretty “coarse grained” and effected by other things going on on the system.  On the other hand, this is probably what really matters when most people consider “running out of memory”.

As shown by [this A/A test](https://github.com/faster-cpython/benchmarking/blob/main/results/bm-20240215-3.13.0a3%2B-aaf8974/bm-20240215-linux-x86_64-mdboom-aa_test-3.13.0a3%2B-aaf8974-vs-base-mem.png), the variability in the results is only 0.16% overall, so is much better than the ~2% we see for timings.

If we need a more accurate number, we can add stats about the size of all objects allocated / deallocated (probably as part of the pystats system).  

We also don't have any data on Windows, since pyperf doesn't support the equivalent system call there.

The summary tables now include a memory usage change number (the last number `(Y.Zx m)`):

![image](https://github.com/faster-cpython/bench_runner/assets/38294/4cd658b3-ab84-4f8f-916c-265088015e9f)

Each benchmarking summary page includes the memory change number and a link to a plot of per-benchmark memory change against its immediate base.

![image](https://github.com/faster-cpython/bench_runner/assets/38294/24452985-7eb5-4d46-ab6d-9096a2e1b351)

![image](https://github.com/faster-cpython/bench_runner/assets/38294/a30822bb-0dca-41c4-9c5a-2a4409d99ed6)

Lastly, there is a [memory longitudinal summary page](https://github.com/faster-cpython/benchmarking/blob/main/memory.md) showing the change of memory over time, and under different configurations:

![image](https://github.com/faster-cpython/bench_runner/assets/38294/8a5e74b3-ef06-4108-bf76-cddcba28a627)

![image](https://github.com/faster-cpython/bench_runner/assets/38294/131de3f5-9b33-460c-95cf-a5eedfb80e0e)

**Comment by brandtbucher** [comment]
Awesome! See https://github.com/python/cpython/issues/116017 for further discussion.
