### ISSUE TITLE
Can't use AWS self-hosted machine for _pystats job

### ISSUE THREAD

**Issue by yuqiw4** [faster-cpython/bench_runner#249]
While we only added an AWS self-hosted machine and try to run the workflow, _pystats job was stuck and waiting forever for a machine to pick up.

The reason probably is that there is a `azure` tag in the template of  _pystats.yml. Can we replace this with `cloud`? https://github.com/faster-cpython/bench_runner/blob/1592e16a6921a6428a7b2812aa2e0245a806342c/bench_runner/templates/_pystats.src.yml#L49

**Comment by yuqiw4** [comment]
cc @mdboom

**Comment by mdboom** [comment]
Sorry for the delay -- just getting back from vacation.

Yes, this was just a bad choice of tag name, and probably should have been `cloud`.

For others who see this bug, they will need to add the `cloud` label to their existing pystats runner following this guide: https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/using-labels-with-self-hosted-runners
