### ISSUE TITLE
notify / notify job is failing after skipping publish / mirror job

### ISSUE THREAD

**Issue by yuqiw4** [faster-cpython/bench_runner#271]
As titled, here is the screenshot:
<img width="1890" alt="Screenshot 2024-09-12 at 12 06 03 AM" src="https://github.com/user-attachments/assets/5468b9f9-0953-4000-9036-f45302c4479c">
and the link to the log:
https://github.com/facebookexperimental/free-threading-benchmarking/actions/runs/10819936093/job/30027186768

Should we remove [this line](https://github.com/faster-cpython/bench_runner/blob/0069b00375acb3d84d7a54a230518beea3bc37ec/bench_runner/scripts/install.py#L200) ? 

Or we can just remove notify / notify job if we decide to skip publish / mirror job. 

cc. @mdboom

**Comment by yuqiw4** [comment]
> Sorry, this needs docs. What this does is it puts a comment on an issue in your benchmarking repository (which then sends a notification through the Github notification system, which may result in an e-mail if the user has configured it that way). It's failing because it's trying to add a comment to issue #0, which doesn't exist.
> 
> If you:
> 
> * create a new issue in your repo
> * Add it's issue number to `[notify]/notification_issue = N` in `bench_runner.toml`
> 
> Does that work? If so, I think all we need to do is add these instructions to the README.md

Oh my concern is that I saw it's trying to do something in `f"(https://github.com/{github_repo}-public/tree/main/results/{dirname})"` but this repo doesn't exist.

**Comment by yuqiw4** [comment]
> Oh my concern is that I saw it's trying to do something in `f"(https://github.com/{github_repo}-public/tree/main/results/{dirname})"` but this repo doesn't exist. We don't have a public repo.

Oh sorry! Never mind! It's just the notification body instead of really doing something in the public repo. I will try to create a new issue and see if that works. Thanks

**Comment by mdboom** [comment]
Makes sense -- it probably also should be configurable where those links point to, since, as you say, you don't have a public repo so those links won't go anywhere useful.  Maybe we change the code so it doesn't add the `-public` if the `publish` configuration is turned off...
