### ISSUE TITLE
Additional Result Comparison request

### ISSUE THREAD

**Issue by yuqiw4** [faster-cpython/bench_runner#276]
Now when we started two workflows, one with no flag, another with NOGIL enabled, then the bench_runner will output:
1. Merge base (no flag) vs PR/ref (no flag)
2. Merge base (NOGIL) vs PR/ref (NOGIL)

Can we also add an additional comparison:
- Merge base (no flag) vs PR/ref (NOGIL)

**Comment by yuqiw4** [comment]
I've done some investigation and think we might be able to achieve it by revising some methods in `result.py`. 

cc @mdboom , please let me know your thought. Thank you soooo much!

**Comment by mdboom** [comment]
Yep, that seems like a good idea, but maybe we should make it a configuration option.  We don't want to do all possible comparisons for space reasons.  We didn't think this was an important one for *our* team's results, but I can completely understand how it would be for someone else's.
